# Generated by Django 3.1.3 on 2020-11-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_road_name', models.CharField(max_length=10)),
                ('address_road_code', models.CharField(max_length=30)),
                ('address_si_gun_gu', models.CharField(max_length=10)),
                ('address_si_do', models.CharField(max_length=10)),
                ('address_post_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='member_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_join_date', models.DateTimeField(auto_now=True)),
                ('member_manager', models.BooleanField(default=False)),
                ('member_total_price', models.IntegerField(default=0)),
                ('member_rank', models.CharField(default='VIP', max_length=20)),
                ('member_password', models.CharField(max_length=15)),
                ('member_id', models.CharField(max_length=18)),
                ('member_contact_number', models.IntegerField()),
                ('member_name', models.CharField(max_length=20)),
                ('member_email', models.CharField(max_length=50)),
                ('member_address', models.CharField(max_length=100)),
                ('member_address_detail', models.CharField(max_length=100)),
                ('member_discount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='product_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Price', models.IntegerField()),
                ('product_register_date', models.DateTimeField(auto_now=True)),
                ('product_made_date', models.CharField(max_length=20)),
                ('product_name', models.CharField(db_index=True, max_length=50)),
                ('product_image', models.ImageField(blank=True, upload_to='product')),
                ('product_description', models.CharField(blank=True, max_length=1000)),
                ('product_volume', models.CharField(max_length=10)),
                ('product_stock', models.IntegerField()),
                ('product_category', models.CharField(max_length=20)),
                ('product_size', models.CharField(max_length=20)),
                ('product_brand', models.CharField(max_length=20)),
                ('product_manufacturer', models.CharField(max_length=20)),
                ('product_meterial', models.CharField(max_length=20)),
                ('product_made_country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='order_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.IntegerField()),
                ('order_pay_status', models.CharField(default='미결제', max_length=10)),
                ('order_mathod', models.CharField(max_length=2)),
                ('order_quantity', models.IntegerField()),
                ('order_transport_number', models.CharField(default=0, max_length=50)),
                ('order_bank', models.CharField(max_length=14)),
                ('order_deposit_person', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(default='미결제', max_length=6)),
                ('order_delivery_company', models.CharField(default='준비중', max_length=20)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.member_tbl')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.product_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='m2mfaq_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_status', models.CharField(default=0, max_length=1)),
                ('comment_image', models.ImageField(null=True, upload_to='m2m')),
                ('comment_write_date', models.DateTimeField(auto_now=True)),
                ('comment_title', models.CharField(max_length=50)),
                ('comment_question', models.CharField(max_length=1000)),
                ('comment_category', models.CharField(max_length=10)),
                ('member_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.member_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='faq_answer_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_description', models.CharField(max_length=1000)),
                ('answer_write_date', models.DateTimeField(auto_now=True)),
                ('answer_writer', models.CharField(default='관리자', max_length=3)),
                ('comment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.m2mfaq_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='cart_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_product_price', models.IntegerField()),
                ('cart_quantity', models.IntegerField()),
                ('member_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.member_tbl')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.product_tbl')),
            ],
        ),
    ]
